import { describe, expect, it } from "vitest";

import {
  buildSlackBlocksTemplate,
  encodeSlackBlockActionValue,
  extractSlackBlockActionsPayloadFromEnvelope,
  normalizeSlackBlockActionPayload,
  normalizeSlackBlocksInput,
} from "./slack-block-kit.js";

describe("normalizeSlackBlocksInput", () => {
  it("accepts a JSON array of block objects", () => {
    expect(
      normalizeSlackBlocksInput([
        { type: "section", text: { type: "mrkdwn", text: "hello" } },
        { type: "divider" },
      ]),
    ).toEqual([{ type: "section", text: { type: "mrkdwn", text: "hello" } }, { type: "divider" }]);
  });

  it("rejects non-array input", () => {
    expect(() => normalizeSlackBlocksInput({ type: "section" })).toThrow(
      "Slack blocks must be a JSON array of objects.",
    );
  });
});

describe("buildSlackBlocksTemplate", () => {
  it("builds a code snippet template", () => {
    const result = buildSlackBlocksTemplate({
      template: "code_snippet",
      title: "Sample code",
      text: "Use this helper.",
      language: "ts",
      code: "const answer = 42;",
      footer: "Generated by pi",
    });

    expect(result.blocks[0]).toMatchObject({ type: "header" });
    expect(JSON.stringify(result.blocks)).toContain("```ts\\nconst answer = 42;");
    expect(result.fallbackText).toContain("Sample code");
  });

  it("builds a status report template with fields", () => {
    const result = buildSlackBlocksTemplate({
      template: "status_report",
      title: "Deploy status",
      text: "All checks passed.",
      fields: [
        { label: "Branch", value: "main" },
        { label: "Commit", value: "abc123" },
      ],
      footer: "Ready to merge",
    });

    expect(result.blocks).toMatchObject([
      { type: "header" },
      { type: "section" },
      { type: "section", fields: expect.any(Array) },
      { type: "divider" },
      { type: "context" },
    ]);
    expect(result.fallbackText).toContain("Branch: main");
  });

  it("builds an action buttons template", () => {
    const result = buildSlackBlocksTemplate({
      template: "action_buttons",
      title: "Review",
      text: "Choose an action.",
      buttons: [
        { text: "Approve", action_id: "review.approve", style: "primary", value: "approve" },
        { text: "Reject", action_id: "review.reject", style: "danger", value: "reject" },
      ],
    });

    expect(result.blocks[2]).toMatchObject({
      type: "actions",
      elements: [
        expect.objectContaining({ action_id: "review.approve", style: "primary" }),
        expect.objectContaining({ action_id: "review.reject", style: "danger" }),
      ],
    });
    expect(result.fallbackText).toContain("Actions: Approve, Reject");
  });

  it("builds a diff view template", () => {
    const result = buildSlackBlocksTemplate({
      template: "diff_view",
      title: "router.ts",
      before: "old line",
      after: "new line",
    });

    expect(JSON.stringify(result.blocks)).toContain("-old line");
    expect(JSON.stringify(result.blocks)).toContain("+new line");
  });
});

describe("encodeSlackBlockActionValue", () => {
  it("passes through strings and encodes objects as JSON", () => {
    expect(encodeSlackBlockActionValue("approve")).toBe("approve");
    expect(encodeSlackBlockActionValue({ action: "approve", issue: 27 })).toBe(
      '{"action":"approve","issue":27}',
    );
  });
});

describe("extractSlackBlockActionsPayloadFromEnvelope", () => {
  it("extracts block_actions payloads from interactive envelopes", () => {
    expect(
      extractSlackBlockActionsPayloadFromEnvelope({
        type: "interactive",
        payload: JSON.stringify({ type: "block_actions", actions: [] }),
      }),
    ).toEqual({ type: "block_actions", actions: [] });
  });

  it("ignores non-interactive envelopes", () => {
    expect(
      extractSlackBlockActionsPayloadFromEnvelope({
        type: "events_api",
        payload: { type: "block_actions" },
      }),
    ).toBeNull();
  });
});

describe("normalizeSlackBlockActionPayload", () => {
  it("normalizes a block action into an inbox event with structured metadata", () => {
    const event = normalizeSlackBlockActionPayload({
      type: "block_actions",
      trigger_id: "trigger-1",
      user: { id: "U123" },
      channel: { id: "C123" },
      container: {
        channel_id: "C123",
        message_ts: "123.456",
        thread_ts: "123.000",
      },
      actions: [
        {
          action_id: "review.approve",
          block_id: "review-actions",
          type: "button",
          text: { type: "plain_text", text: "Approve" },
          value: '{"decision":"approve","pr":212}',
          action_ts: "123.789",
          style: "primary",
        },
      ],
    });

    expect(event).toEqual({
      channel: "C123",
      threadTs: "123.000",
      userId: "U123",
      text: 'Clicked Slack "Approve" (action_id: review.approve).',
      timestamp: "123.789",
      metadata: {
        kind: "slack_block_action",
        actionId: "review.approve",
        blockId: "review-actions",
        value: '{"decision":"approve","pr":212}',
        parsedValue: { decision: "approve", pr: 212 },
        actionText: "Approve",
        channel: "C123",
        threadTs: "123.000",
        messageTs: "123.456",
        actions: [
          {
            actionId: "review.approve",
            blockId: "review-actions",
            text: "Approve",
            type: "button",
            style: "primary",
            value: '{"decision":"approve","pr":212}',
            parsedValue: { decision: "approve", pr: 212 },
            actionTs: "123.789",
          },
        ],
      },
    });
  });

  it("falls back to message ts when thread ts is absent", () => {
    const event = normalizeSlackBlockActionPayload({
      type: "block_actions",
      user: { id: "U123" },
      channel: { id: "D123" },
      container: {
        channel_id: "D123",
        message_ts: "222.333",
      },
      actions: [
        {
          action_id: "task.done",
          type: "button",
          text: { type: "plain_text", text: "Done" },
        },
      ],
    });

    expect(event?.threadTs).toBe("222.333");
    expect(event?.timestamp).toBe("222.333");
  });
});
